version: '3.8'

services:

  api:
    build: .
    command:
      - /bin/bash
      - -c
      - |
        alembic upgrade head
        uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - '8000:8000'
    env_file:
      - ./.env
    depends_on:
      pgdb:
        condition: service_healthy
    links:
      - pgdb

  pgdb:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    volumes:
      - pg_db_vol:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 10s
      timeout: 60s
      retries: 5
      start_period: 80s

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5050:80"
    env_file:
      - ./.env
    volumes:
      - pg_admin_vol:/var/lib/pgadmin

volumes:
  pg_db_vol:
  pg_admin_vol: